### ISSUE TITLE
How to bind crystal closures  in the engine?

### ISSUE THREAD

**Issue by ray-delossantos** [jessedoyle/duktape.cr#12]
``` crystal
  sbx = Duktape::Sandbox.new

  sbx.push_global_object

  test = 10
  sbx.push_proc(2) do |ptr| # 2 stack arguments
    env = Duktape::Sandbox.new ptr
    a = env.get_number 0
    test = env.get_number 1
    env.push_number a + test
    env.return 1 # return success
  end

  sbx.put_prop_string -2, "adder"
  sbx.eval! "print(adder(2, 3));" # => 5
```

this returns

```
passing a closure to C is not allowed
```

**Comment by jessedoyle** [comment]
Passing closures to C bindings is not allowed in Crystal ([relevant link](http://crystal-lang.org/docs/syntax_and_semantics/c_bindings/callbacks.html)).

The reason that the compiler is detecting that a closure is passed and not simply a Proc is because you are aliasing the variable `test` defined in scope outside of the Proc.

I've encountered this issue previously, but I believe it's simply an issue with the way C bindings are handled - I don't think there is much that can be done to solve it. That's one major reason why I consider passing procs to Duktape as experimental (I also use variable names such `env` in examples to reduce the chance of this occurring).

If you want to pass data/variables from Crystal to the Duktape engine, you almost certainly need to use the stack:

``` crystal
sbx = Duktape::Sandbox.new

num = 10
sbx.push_proc(2) do |ptr| # 2 stack arguments
  env = Duktape::Sandbox.new ptr
  a = env.get_number 0
  test = env.get_number 1
  env.push_number a + test
  puts "NUM: #{a + test}"
  env.return 1 # return success
end

sbx << 1    # push first arg
sbx << num  # push second arg
sbx.call(2) # call the function with 2 arguments
```

**Comment by jessedoyle** [comment]
It's also worth noting that the `push_proc` method is currently just a thin wrapper to Duktape's `duk_push_c_function` API call ([link](https://github.com/jessedoyle/duktape.cr/blob/master/src/duktape/api/push.cr#L136-L138)).

I would be open to any ideas to make this call simpler or less error-prone. Pull requests would also be more than welcome :smile:

**Comment by ray-delossantos** [comment]
Excellent overview of the problem, thanks for your help. 
Is there any way to extract from the stack a global variable with a complex object. Example:

``` javascript
{
"test": 100.
"test2": {
  "subtest1": 1,
  "subtest2": "string test"
 }
}
```

Right now i'm using JSON.Stringify() to extract a string with this object json and in crystal i'm using JSON.Parse(string_from_stack). Just wanted to now if there's a better kind of serialization for a class type with this library.

**Comment by ray-delossantos** [comment]
@jessedoyle , waj responded about this behavior in this issue https://github.com/manastech/crystal/issues/2029 , and gave some tips about how to do it. i'm a newbie in crystal and C, maybe you could have a better idea on how to implement his suggestions.

**Comment by jessedoyle** [comment]
You should take a look at the `Runtime` code that I recently wrote. Here's a [link to the code](https://github.com/jessedoyle/duktape.cr/blob/master/src/duktape/runtime.cr#L173-L193).

The code uses the `object_to_crystal`, `stack_to_crystal`, `next_hash_element` and `next_array_element` methods to take a complex JS object on the stack and convert it to a usable Crystal value.

I'm unsure of your exact use-case, but you should be able to reuse a lot of my code from the `Runtime` class to achieve the results you want.

**Comment by ray-delossantos** [comment]
Ooops, my mistake for overlooking the Runtime code. Kudos to you for the amazing high level api for this shard. 
I'll try to figure out the closure detail or use a workaround for my project.
Again, thanks for this amazing work.

**Comment by jessedoyle** [comment]
You can definitely use the low-level API to pass complex data from Crystal to Duktape and vice-versa, but the data is going to have to go through the Duktape stack first (as opposed to being returned as a void pointer or something).  

The `Runtime` code should be very useful to you because it takes complex Crystal objects (Hashes, Arrays) and pushes them to the stack. It also takes stack values and converts them back to Crystal Arrays and Hashes.

If you find a good solution to your problem, feel free to send a PR back my way!

**Comment by jessedoyle** [comment]
Im going to leave this issue open for a little bit as I think of ways to alter `push_proc` to make it more streamlined.

**Comment by jessedoyle** [comment]
Okay so I've done some thinking about how the `push_proc` method works:
- I don't think that we need to focus on making closures passable to the Duktape runtime. Instead, data/variables from the Crystal side should be passed as arguments to the JS function via the Duktape stack.
- This means that Crystal will consider the proc to be a closure if it aliases any variable names outside the scope of the proc. We should document this behaviour in the README.

What I would really like for the `push_proc` API is something like:

``` crystal
sbx = Duktape::Sandbox.new
sbx.push_proc(2) do |env|
  a = env.get_number 0
  b = env.get_number 1
  env << a + b
  env.call_success
end
```

In the above case, `env` is automatically passed as a `Duktape::Sandbox` instance, and it is not necessary to wrap any pointers in a `Duktape::Sandbox` object.

Unfortunately, I don't think this behaviour is currently possible. Of course I could be missing a simple detail - if anyone has an idea to implement the API above please let me know or open a PR.

With that being said, I recently implemented `env.call_failure`, `env.call_success` and `env.return_undefined` that will provide the engine with the appropriate integer status codes.

Finally, I also implemented `push_global_proc`:

``` crystal
sbx = Duktape::Sandbox.new
sbx.push_global_proc("add_one", 1) do |ptr|
  env = Duktape::Sandbox.new ptr
  num = env.get_number 0
  env << num + 1
  env.call_success
end

sbx.eval!("print(add_one(41));") # => 42
```

**Comment by jessedoyle** [comment]
@raydf - Just FYI to anyone looking at this issue:

I made a [comment](https://github.com/jessedoyle/duktape.cr/issues/23#issuecomment-354519313) in another issue and came to the realization that closure data can be passed through the Duktape stack as a pointer.

See [here](https://github.com/jessedoyle/duktape.cr/issues/23#issuecomment-354519313) for a functioning example.
