### ISSUE TITLE
Is the project maintained? - [edit: Yes, it is!]

### ISSUE THREAD

**Issue by vladfaust** [jessedoyle/duktape.cr#46]
Hello,

I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date. Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by jessedoyle** [comment]
Hi @vladfaust!

I realize that this issue was opened by a bot, but here's a response to your question:

This shard is actively maintained by myself, and I try to (semi) regularly update this project to conform with new releases of Crystal and Duktape.

> I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date.

This project has a comprehensive test suite [here](https://github.com/jessedoyle/duktape.cr/tree/master/spec) - everything seems to pass for me with Crystal 0.26.1.

I pushed a test branch to Travis CI to make sure it wasn't just something local to my machine. From what I can see the build is successful: https://travis-ci.org/jessedoyle/duktape.cr/builds/430741570.

Perhaps there's a bug somewhere in your automated script?

For now I'm going to close this issue, but feel free to respond! If there's a legitimate issue, I'd love to resolve it.

Thanks!

**Comment by vladfaust** [comment]
I've tested the shards automatically, but all about 50 issues have been opened manually 😅 Thanks for the response, @jessedoyle! Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build begins to fail: https://docs.travis-ci.com/user/cron-jobs.
