### ISSUE TITLE
Duktape::Runtime - functions require at least a parameter

### ISSUE THREAD

**Issue by dinh** [jessedoyle/duktape.cr#57]
**This triggers error**
```
require "duktape/runtime"

  # A Runtime (optionally) accepts an initialization block
  rt = Duktape::Runtime.new do |sbx|
    sbx.eval! <<-JS
      function test() { return "this does not work unless test has a parameter"; }
    JS
  end

  rt.call("test") # => error
```
**this work**
```
require "duktape/runtime"

  # A Runtime (optionally) accepts an initialization block
  rt = Duktape::Runtime.new do |sbx|
    sbx.eval! <<-JS
      function test(dummy param) { return "this works"; }
    JS
  end

  rt.call("test", "thisisadummyparam") # => works
```

**Comment by jessedoyle** [comment]
Hey @dinh, thanks for using Duktape!

I'm able to reproduce the issue - you've definitely stumbled upon a bug!

The issue doesn't throw any exceptions/errors, but the problem is that the function never actually gets called when using the `call` runtime method without arguments.

The bug stems from this logic: https://github.com/jessedoyle/duktape.cr/blob/6fa1f4f762909549a676af6f7d0acb2f34452e94/src/duktape/runtime.cr#L231. 

If no arguments are passed to the `call` method, then we just _read_ the property instead of calling the function. This allows us to read constants and properties that are namespaced (such as `Math.PI`, but doesn't work correctly for all cases.

I suspect a fix is to include a call to `@context.is_callable` in the condition when with no arguments. Essentially, if the property is callable, then we call it (as opposed to only reading it).

I'll be able to dig in more over the next few days, but PRs are welcome if anyone wants to submit a bug fix.

**Comment by jessedoyle** [comment]
Hi @dinh - I created a PR here: https://github.com/jessedoyle/duktape.cr/pull/58.

Are you able to verify that this fixes your issue?

Thanks!

**Comment by jessedoyle** [comment]
I'm going to merge #58 and cut a new `0.19.1` release that includes a fix to this bug!
